Update README.md
brownplt/insta-model pull request #3
Opened 2022-04-22 03:21 UTC by LuKC1024

2022-04-22 15:05 UTC, bennn requested changes

2022-04-22 15:05 UTC, bennn commented on README.md
> +If you look at [the definition of `compile-check` in `./compile.rkt`](https://github.com/brownplt/insta-model/blob/c9f21f5479b2dd4f9ddbfabacba88d22b3cb1811/compile.rkt#L1225), the `dynamic` case is t
> a test for the none value and a recursive call

Replace "recursive call" with "tag check" or "recursive tag check".

With the current two sentences, it looks like the overall check for `Optional[T]` is a tag check.

(Another fix would be to change the final sentence: replace "the check must be" with "the recursive call must perform". But I'd rather we keep the text as short as possible.)

2022-04-23 20:01 UTC, LuKC1024 commented on README.md
> +
Fixed by [f07d5df](https://github.com/brownplt/insta-model/pull/3/commits/f07d5df017c79eef604335740bda39697e6c5ef3)

2022-04-23 20:12 UTC, LuKC1024 commented on README.md
> +It is easy to find those language constructs in [./conformance_suite](./conformance_suite).
That makes a lot of sense. Fixed in 0a5a73e and 67eb471.

2022-04-23 21:02 UTC, LuKC1024 commented on README.md
> +We have two uses of [`redex-check`](https://docs.racket-lang.org/redex/reference.html#%28form._%28%28lib._redex%2Freduction-semantics..rkt%29._redex-check%29%29) in [./conjectures.rkt](./conjectures.
Resolved.

2022-04-23 21:07 UTC, LuKC1024 commented on README.md
> +If you look at [the definition of `compile-check` in `./compile.rkt`](https://github.com/brownplt/insta-model/blob/c9f21f5479b2dd4f9ddbfabacba88d22b3cb1811/compile.rkt#L1225), the `dynamic` case is t
Fixed in d071cbf890ad722b2508c0a0ed9f1c5cb307ec29

2022-04-23 23:06 UTC, bennn approved these changes

2022-04-23 23:06 UTC, bennn commented on README.md
> +In the repository we tested 10000 random expressions and 15000 random programs. The numbers are different in the paper (1600 and 11000) but you can always change the numbers.
The numbers in the paper are about **well-typed** terms, not random terms.
(I'll reword this).

2022-04-23 23:06 UTC, bennn commented on README.md
> +If you look at [the definition of `compile-check` in `./compile.rkt`](https://github.com/brownplt/insta-model/blob/c9f21f5479b2dd4f9ddbfabacba88d22b3cb1811/compile.rkt#L1225), the `dynamic` case is t
"We introduced ...." makes it sound like SP doesn't have function types internally. But it does!
(I'll fix)

2022-04-23 23:06 UTC, merged

2022-04-24 17:03 UTC, bennn commented on README.md
> +We will walk you through the first use. The other is very similar. On line 172 you will see the following expression. The expression generate 10000 random expressions (`e+`) and checks whether for al
heads up: "nonterminate `e+`" should be "nonterminal `e+`"
(I'll fix)